stages:
  - build

# Cache for Go dependencies
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

# Build and test mllint. Runs only on non-protected branches (i.e. everything that's not 'main')
build+test:
  stage: build
  image: golang:1.15-buster
  extends: .go-cache
  script:
    - go get github.com/t-yuki/gocover-cobertura
    - make build-local
    - make test-coverage
    - $GOPATH/bin/gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      cobertura: coverage.xml
  except:
    refs:
      - main # protected branch, CI will run on GitHub Actions.
