stages:
  - build

# Cache for Go dependencies
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

# Build and test mllint
build+test:
  stage: build
  image: golang:1.15-buster
  extends: .go-cache
  script:
    - go get github.com/t-yuki/gocover-cobertura
    - go build -o mllint .
    - go test -v -cover -coverprofile=coverage.txt ./...
    - $GOPATH/bin/gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      cobertura: coverage.xml
  except:
    changes:
      - .gitignore
      - ReadMe.md