# This .goreleaser.yml file configures GoReleaser to properly and reproducibly build `mllint` for Linux, MacOS and Windows
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - -s -w -X github.com/bvobart/mllint/commands.version={{.Version}} -X github.com/bvobart/mllint/commands.commit={{.Commit}} -X github.com/bvobart/mllint/commands.date={{.CommitDate}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
