package dependencymgmt

// This array holds the names of all (known) dependencies that should always be dev dependencies, not normal dependencies.
// Of course, feel free to extend this if necessary!
var ShouldBeDevDependencies = []string{
	"bandit",
	"black",
	"coverage",
	"darglint",
	"dvc",
	"flake8",
	"flake8-bandit",
	"flake8-bugbear",
	"flake8-docstrings",
	"flake8-rst-docstrings",
	"flakehell",
	"isort",
	"mccabe",
	"mllint",
	"mypy",
	"pandas-vet",
	"pep8-naming",
	"poethepoet",
	"pre-commit",
	"pre-commit-hooks",
	"pyflakes",
	"Pygments",
	"pylama",
	"pylint",
	"pytest",
	"pytest-cov",
	"reorder-python-imports",
	"safety",
	"sphinx",
	"sphinx-rtd-theme",
	"sphinx-click",
	"tox",
	"typeguard",
	"xdoctest",
}
