name: Build mllint and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:

  build_golang:
    name: Build and test mllint's Golang source code on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          # In order:
          # * Go module download cache
          # * Go build cache (Linux)
          # * Go build cache (Mac)
          # * Go build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ubuntu-latest-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ubuntu-latest-go-

      - name: Run mllint tests
        run: make test

      - name: Build mllint executables
        run: make build-all

      - uses: actions/upload-artifact@v2
        with:
          name: mllint-binaries
          path: ./build/bin/*

  build_wheels:
    name: Build Pip wheels on ${{ matrix.os }}
    needs: build_golang
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2

      - name: Download mllint executables from previous job
        uses: actions/download-artifact@v2
        with:
          name: mllint-binaries
          path: ./build/bin

      - name: Prepare packaging
        run: make pre-package

      - name: Build Pip wheels
        uses: joerick/cibuildwheel@v1.10.0
        with:
          package-dir: ./build
          output-dir: ./build/wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          name: pip-wheels
          path: ./build/wheelhouse/*.whl

  build_sdist:
    name: Build Pip package source distribution
    needs: build_golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Download mllint executables from previous job
        uses: actions/download-artifact@v2
        with:
          name: mllint-binaries
          path: ./build/bin

      - name: Prepare packaging
        run: make pre-package

      - name: Build Pip package source distribution
        working-directory: ./build
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: pip-source-package
          path: ./build/dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: pip-source-package
          path: dist
      - uses: actions/download-artifact@v2
        with:
          name: pip-wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
